# fly.toml app configuration file generated for backend-damp-leaf-8400 on 2025-07-26T10:45:56-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-damp-leaf-8400'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

# --- SECCIÓN AÑADIDA PARA MONTAR EL VOLUMEN ---
# Esto conecta el volumen 'logos_data' a la carpeta '/code/logos' de tu aplicación,
# haciendo que el almacenamiento de los logos sea permanente.
[mounts]
  source="logos_data"
  destination="/code/logos"
